### ISSUE TITLE
请问有没有用BLS做增量学习的API接口?

### ISSUE THREAD

**Issue by njuptlht** [MPX0222/BroadLearningSystemTools-2.0#1]
当新的数据来临，甚至带着新的类别时，可不可以用BLS做样本增量或者类增量呢？

**Comment by MPX0222** [comment]
在理论上是支持增量学习的，但目前API还不支持哈

**Comment by njuptlht** [comment]
> 在理论上是支持增量学习的，但目前API还不支持哈

你好，我在测试代码的时候还有个问题，在我在调用StackedBroadLearningSystem.py的类StackBLSClassifier里的fit函数时，第20行报错“block_fit_pred = block_module.fit(train_x, block_train_y)”，报错内容是“AttributeError: 'BLS' object has no attribute 'fit'”，问题应该是block_module调用BLS时没有找到fit函数，请问你有遇到这个问题么？

**Comment by MPX0222** [comment]
感谢您指出的问题，我已经对这处代码进行修改😁

**Comment by njuptlht** [comment]
> 感谢您指出的问题，我已经对这处代码进行修改😁
看到了你在StackedBroadLearningSystem.py的19行block_module = BLSClassifier(is_argmax=False)的修改，但是会报错没有“is_argmax=False”这个关键词，如果直接去掉也会报错维度不匹配。可以在测试阶段调用StackBLSClassifier试试分类的效果，目前调用这个还没跑成功

**Comment by njuptlht** [comment]
> 感谢您指出的问题，我已经对这处代码进行修改😁

看到了你在StackedBroadLearningSystem.py的19行block_module = BLSClassifier(is_argmax=False)的修改，但是会报错没有“is_argmax=False”这个关键词，如果直接去掉也会报错维度不匹配。可以在测试阶段调用StackBLSClassifier试试分类的效果，目前调用这个还没跑成功

**Comment by MPX0222** [comment]
@njuptlht 我已经再次修改，您可以再次在demo中对代码进行测试，谢谢！
